{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentops.serviceAccountName" . }}
  labels:
    {{- include "agentops.labels" . | nindent 4 }}
{{- end }}
