{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent.serviceAccountName" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secretManager.enabled }}
    iam.gke.io/gcp-service-account: {{ .Values.secretManager.serviceAccount }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
